### ISSUE TITLE
Overriding serviceUrl

### ISSUE THREAD

**Issue by levimatheri** [SSanjeevi/APIM-Devops-Sample-Pipeline#2]
The serviceUrl parameter generated is an object. How do you override it for different APIs in your CI/CD pipeline?

**Comment by VidhyaSanjeevi** [comment]
Use service url parameters to give json file path of a json file with name of api in valid yml and value with url.

**Comment by levimatheri** [comment]
Thanks! Was able to get it working by passing `--backendurlconfigFile` to creator tool with path to json file.

**Comment by levimatheri** [comment]
@SSanjeevi Question: We have a lot of APIs (about 50) and Extractor seems like a good tool to extract ARM templates for all of them. We'd like for developers to push a swagger file for an API if they make changes rather than making changes to the extracted templates. How would we go about this? Would we need to create a config.yml for all APIs in order to use Creator tool?
